import asyncio
from typing import Dict, Any

class OpenCodeProxy:
    def __init__(self, api_url: str):
        self.api_url = api_url

    async def generate_code(self, prompt: str, language: str, session_id: str) -> str:
        # Simulate network delay
        await asyncio.sleep(2)
        
        # Mock response based on input
        return f"""
# Here is the generated code for: {prompt}
# Language: {language}
# Session: {session_id}

def solve_problem():
    print("This is a mock solution generated by OpenCode Proxy")
    return True
"""

    async def debug_code(self, code: str, error: str, session_id: str) -> str:
        await asyncio.sleep(1.5)
        return f"""
# Debug Analysis
The error '{error}' seems to be caused by a simulated issue.
Here is the fix:

# Fixed code
{code}
# ... patched ...
"""

    async def refactor_code(self, code: str, focus: str, session_id: str) -> str:
        await asyncio.sleep(1.5)
        return f"""
# Refactoring for: {focus}

# Optimized Code
{code}
# ... optimized ...
"""

# Global instance
# We import settings inside to avoid circular imports if any, 
# but here it is clean.
from core.config import settings
opencode_client = OpenCodeProxy(settings.opencode_api_url)
